# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.IntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')])),
            ],
        ),
    ]
